
  name: CI Workflow
  
  on:
    push:
      branches:
        - main
        - 'release/*'
    pull_request:
      branches:
        - main
    schedule:
      - cron: '0 0 * * 0'  # Cada domingo a medianoche
    workflow_dispatch:
    release:
      types: [published]
  
  jobs:
    test:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Ver files
          run: |
            ls
            pwd
  
        - name: Set up Node.js
          uses: actions/setup-node@v2
          with:
            node-version: '14'
  
        - name: Install dependencies
          run: npm install

    deploy:
      runs-on: ubuntu-latest
      needs: test
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
      
        - name: Deploy project
          run: echo "esto es un deployment"


    notificacion:
      runs-on: ubuntu-latest
      steps:
        - name: Envio de email
          run: echo "enviando email"
