name: Run script
on: 
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run build script
        run: |
          ls
          cd scripts
          ls
          ./build.sh

      - name: Run build script
        run: |
          ./scripts/build.sh
