name: Variable Example
on: [push, workflow_dispatch]
env:
  WORKFLOW_VAR: "This is a workflow-level variable"

jobs:
  build:
    environment: test
    runs-on: ubuntu-latest
    env:
      JOB_VAR: "This is a job-level variable"
    steps:
      - name: Print workflow-level variable
        run: echo "Workflow variable ${{ env.WORKFLOW_VAR }}"

      - name: Print job-level variable
        run: echo "Job variable ${{ env.JOB_VAR }}"

      - name: Set step-level variable
        env:
          STEP_VAR: "This is a step-level variable"
        id: set_step_var
        run: |
          echo echo 'NAME=This is a bash-level variable' >> GITHUB_ENV
          echo "var= ${{ vars.STEP_VAR }}"
          echo "env= ${{ env.STEP_VAR }}"
          echo "env_custom= ${{ env.NAME }}"

      - name:  variable env
        run: echo "variable ${{ env.VAR_TEST }}"
