name: Variable Example
on: [push]
env:
  WORKFLOW_VAR: "This is a workflow-level variable"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      JOB_VAR: "This is a job-level variable"
    steps:
      - name: Print workflow-level variable
        run: echo "Workflow variable ${{ env.WORKFLOW_VAR }}"

      - name: Print job-level variable
        run: echo "Job variable ${{ env.JOB_VAR }}"

      - name: Set step-level variable
        env:
          STEP_VAR: "This is a step-level variable"
        id: set_step_var
        run: |
          echo echo 'name=This is a step-level variable' >> GITHUB_ENV
          echo "var= ${{ vars.STEP_VAR }}"

